CREATE DATABASE IF NOT EXISTS quiz_db CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE quiz_db;

CREATE TABLE IF NOT EXISTS quiz (
  id INT AUTO_INCREMENT PRIMARY KEY,
  question VARCHAR(256) NOT NULL,
  answer VARCHAR(256) NOT NULL
);
